server:
  port: 18087
spring:
  datasource:
    url: jdbc:h2:file:./db/mydb;DATABASE_TO_UPPER=false;
    username: sa
    password: password

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
        ddl-auto: none
  h2:
    console.enabled: true
